export const ADD_MUSIC ="ADD_MUSIC";
export const DELETE_MUSIC ="DELETE_MUSIC";
export const UPDATE_MUSIC ="UPDATE_MUSIC";
export const MUSIC_LIST ="MUSIC_LIST";
export const SET_MUSIC_LIST ="SET_MUSIC_LIST";
export const SELECTED_MUSIC="SELECTED_MUSIC";
export const MUSIC_TO_UPDATE="MUSIC_TO_UPDATE";
export const SEARCH_MUSIC="SEARCH_MUSIC";